### ISSUE TITLE
Публикация расшифрованных исходников клиентской части

### ISSUE THREAD

**Issue by ghost** [TheQmaks/Fightz.IO-Cheats#1]
Привет! Я знаю, что вы, должно быть, перешли к чему-то другому, но я возобновил вашу работу над сценарием fightz.io, и теперь игра полностью кодифицирована. Я больше ничего не понимаю, возможно, вы сохранили какой-то файл, касающийся исходный код для сайта fightz.io или что-то еще, что мне может пригодиться? Я надеюсь, что вы увидите мое сообщение, и мне бы очень помогло, если бы у вас остались какие-либо архивы, спасибо

**Comment by TheQmaks** [comment]
Раз ты так заинтересовался - ради тебя сделал полный реверс клиентской части, которого даже у меня в своё время не было.
https://github.com/TheQmaks/Fightz.IO-Cheats/blob/master/reversed_clientside.js

**Comment by ghost** [comment]
большое спасибо 🙏
